### ISSUE TITLE
Trying to understand the library

### ISSUE THREAD

**Issue by lsoares** [uberto/kondor-json#1]
Hi Uberto

when you say "To your own domain objects", IMHO the adapters should never try to map into domain objects directly because that would mean coupling the outside world with your app's domain. Even if it's the same domain, I would not map directly into classes anyway. I'd do (using Jackson):

`val jsonNode = objectMapper.readTree(jsonString)`

Then I'd just use that generic `jsonNode` to build my own objects - domain or not:
      
```
jsonNode.run {
    Invoice(
        externalId = InvoiceId(it.at("/id").textValue()),
        vat = it.get("vat-to-pay")?.booleanValue() ?: false,
        description = it.at("/blabla/description")?.textValue(),
        anotherField = it.at("/some/place/0/field") ?: "some default",
    )
}
```

I did not use any reflection, DTOs, nor annotations, right?
It also supports JsonPointers and nullable fields.

PS. [I'm not a fan of making my serializing classes public.](https://levelup.gitconnected.com/stop-testing-your-serializers-9b568ecd652f). Those are implementation details of the adapter and no one needs to see them.

Don't get me wrong. I just want to understand the benefits of using this library so I can add it to my toolbelt and use it when I need it. 💪

**Comment by uberto** [comment]
"the adapters should never try to map into domain objects directly because that would mean coupling the outside world with your app's domain."

I don't agree with this sentence. We are talking about the objects used by the public interface of the domain.

Now, the domain shouldn't know anything about the "outside world" but it's the role of the adapter to adapt the outside world to the domain. If you pass JsonNode to the domain (or any other thing that need to be deserialized again) you are coupling your domain with the specific JsonNode implementation, which is much worse imho.

In any case, Kondor is not much different from what you wrote, only that it's nicer (well at least for me :)), and it gives you both serializer and deserializer together, and better error messages.

In the specific Jackson JsonNode are mutable quite heavy objects, not something I would import in my domain.

But if you really want, you can do the same with Kondor:

val jsonObjectNode = parseJsonNodeObject(JsonLexer().tokenize( jsonString), NodeRoot)

and then

JInvoice.fromJsonNode(jsonObjectNode)

**Comment by lsoares** [comment]
> I don't agree with this sentence. We are talking about the objects used by the public interface of the domain.

I think I misexplained sorry. And I think we agree. The adapter can return domain objects. But I would never annotate domain objects with JSON stuff - as you said. Even if I used JSON annotations, I'd put them in DTOs that only the adapter knows about. Then I'd have to convert them to the domain. Anyway, we agree JSON annotations are not the way.

> If you pass JsonNode to the domain

I'd never do that! :) JSON in the domain is a big no. What I showed you was only the parsing part that belongs to the adapter. It should be private there. What comes out are only `Invoice`s. Therefore, it doesn't matter much if `JsonNode` is mutable because it's used only as a private helper.

> it gives you both serializer and deserializer together, and better error messages

These are great arguments! To me, they're more valid than the others you gave. I'll keep an eye on the library. Thanks for building it!
